### ISSUE TITLE
Fedora spin

### ISSUE THREAD

**Issue by nicktelindert** [nicktelindert/nextspace-build-iso#11]
Generate Fedora packages to use for a Fedora spin. My own system works better with Fedora and i prefer Fedora for the bleeding edge stuff. I can pretty much use the same build script with minor changes.

**Comment by alexmyczko** [comment]
I for one would like a Debian based version.

**Comment by nicktelindert** [comment]
The problem with that is that i need to create a whole new build system. For Fedora i can pretty much use the same process. So if someone wants a debian version they really need to create that spin themselves. I can't create a spin for every distro. Even this one has low priority because i originally only wanted to do it for personal use.

**Comment by doublet30** [comment]
I have a modular open source build system that can produce Installable ISO's.  The source is available at http://git.ttoslinux.org

So far, there is a build module for TTOS Linux that works, and a build module for Debian that somewhat works.  You can create simple modules for any distro type using bash.  The Debian module utilizes the official Debian bootstrap method.  You drop your packages in a packages folder, edit a package list for packages to install from the repositories, and run the build process.  It builds an install ISO that is compatible with USB thumb drives.

**Comment by nicktelindert** [comment]
@doublet30 
Maybe someone else in the community wants to pick it up? I think a more important thing now would be to have the packages build for multiple distros including debian with a CI/CD system distribute it more widely. Maybe in time i will pick that up. But i rather focus on one distro base right now.

**Comment by doublet30** [comment]
My plate is full at the moment.  My current CI/CD implementation is bash scripted, pre-dates current implementations, and is not compatible with git.  I do plan to learn GitLab continuous integration and deployment in the future and I would be more than happy to help at this time.  I would also be willing to host the Debian packages in the TTOS repositories as well.

**Comment by doublet30** [comment]
Create a Fedora build module for TTOS Linux Studio.  I planned on porting a build module for Mageia or OpenMandriva in the near future.  Those are both RPM based distros and have up to date packages as well as easily accessible development channels for bleeding edge packages.  If you don't have time to code a Fedora build module, that might be worth waiting for.

**Comment by doublet30** [comment]
https://youtu.be/0ka_aNs_RG4
That is a YouTube video of TTOS Linux Studio building TTOS.  The Studio app can build other distros as well.  This would be an useful tool for automating up to date builds of an OS image.  The build system uses the latest versions available at build time.

**Comment by nicktelindert** [comment]
@doublet30 to be honest, i really like to stick to kickstart at least for now, because i really like the way it works and i like the simplicity behind it. But in the future i will probably configure a CI/CD setup if no one else steps up. Once that that is set-up it works and doesn't need a lot of maintenance.

**Comment by nicktelindert** [comment]
Not important for now
