### ISSUE TITLE
Audio not working after install

### ISSUE THREAD

**Issue by nicktelindert** [nicktelindert/nextspace-build-iso#12]
Created user is not a member of the audio group.

**Comment by alexmyczko** [comment]
here's how i did all that stuff: https://github.com/alexmyczko/livecd.gnustep.org/blob/master/etc/init.d/autoexec.bat

**Comment by nicktelindert** [comment]
@alexmyczko Anaconda creates the user, so i probably need to edit some configuration file for anaconda. You method wouldn't work in my case. But thanks anyway

**Comment by nicktelindert** [comment]
@alexmyczko i took some inspiration from that, i created an old school init script to add all users to the audio group on boot. Not the most fancy way to do it. But it does work.
