### ISSUE TITLE
After install : new user folder created in /home instead of /Users

### ISSUE THREAD

**Issue by BertrandDekoninck** [nicktelindert/nextspace-build-iso#14]
NextSpace has the same convention as NextStep and OSX for users homes : they should be  created in /Users. The /home folder is hidden in NextSpace file selector and can"t be accessed with it.
After installing the live-cd  (in Virtualbox), the user I created with Anaconda has its home folder in /home instead of /Users, which could lead to navigation issues with the file selector.
For instance in TextEdit, I couldn't navigate with the file selector to a file located in my home. I could only open this file with drag and drop from the Workspace window to TextEdit's appicon on the dock.

**Comment by nicktelindert** [comment]
Fixed on my development release i will add those configuration files to git soon
