### ISSUE TITLE
Login prompt never shows up / it's just slow

### ISSUE THREAD

**Issue by alexmyczko** [nicktelindert/nextspace-build-iso#18]
Just some gray background image showing a 7 when trying with qemu:

`qemu-system-x86_64 -m 1G -cdrom NEXTSPACE.iso`

err wait it shows up, after MINUTES!!!!

the preferences don't look like in the nextspace screenshot but it's all empty (the info panel)

**Comment by nicktelindert** [comment]
I will try it with a newer build which has a lot of fixes, i probably replace the ISO with a new one. the current one is a lot better. But first i create a portable docker build environment and add the dockerfile to git. Thanks for reporting

**Comment by nicktelindert** [comment]
I updated README, you need KVM enabled to get decent performance otherwise it relies entirely on emulation which is much more slower than KVM.
