### ISSUE TITLE
Add base applications

### ISSUE THREAD

**Issue by nicktelindert** [nicktelindert/nextspace-build-iso#3]

**Comment by nicktelindert** [comment]
- Added firefox
- Added gvim

**Comment by trunkmaster** [comment]
Transmission, MPV, Emacs, Dia, GIMP, VirtualBox. I've attached my app wrappers.
[AppWrappers.zip](https://github.com/nicktelindert/nextspace-build-iso/files/4271177/AppWrappers.zip)

**Comment by BertrandDekoninck** [comment]
GNUstep apps : ProjectCenter, Gorm, Gemas, PikoPixel, BattMon. I don't if it is easy because those should be build using Nextspace versions of base and gui. The CentOS rpm packages of gnustep apps will conflict.

**Comment by nicktelindert** [comment]
I now use your packages of gnustep so it should work fine, but i probably should compile it when building the ISO. But that counts for every gnustep app i add. The appwrappers could be a problem, because appwrappers i am working on automatically generating appwrappers after installing apps. That generation process will now update the whole applications directory with new Xappwrappers so it will destroy old wrappers. I will have to add a feature to ignore the system apps so prevent them wrong getting updated.

**Comment by trunkmaster** [comment]
@nicktelindert, I'm afraid it's not possible to create perfect appwrapers for non-GNUstep applications automatically. The perferct appwrapper for NEXTSPACE should contain executable name that consists of WM class and WM name separated by period (emacs.Emacs). You can check it with `xprop` utility and check for `WM_CLASS` value. For example for Emacs xprop's output for `WM_CLASS` is `"emacs", "Emacs"`. So app executable must be named as `emacs.Emacs`.

If executable name is not correct you should observe appicon in launching state after application quit.

**Comment by nicktelindert** [comment]
> @nicktelindert, I'm afraid it's not possible to create perfect appwrapers for non-GNUstep applications automatically. The perferct appwrapper for NEXTSPACE should contain executable name that consists of WM class and WM name separated by period (emacs.Emacs). You can check it with `xprop` utility and check for `WM_CLASS` value. For example for Emacs xprop's output for `WM_CLASS` is `"emacs", "Emacs"`. So app executable must be named as `emacs.Emacs`.
> 
> If executable name is not correct you should observe appicon in launching state after application quit.

Perfect wrappers is indeed impossible. Basic wrappers work fine for me though for only launching stuff.  But i will use mainly the precreated wrappers and keep my script installed for creating a basic wrapper if someone needs it.
